run: proposed-iter1-Llama-2-7B-HF-4-bit-QLoRA-7-B-parameters
results_dir: .research/iteration1
mode: trial
wandb:
  entity: gengaru617-personal
  project: 2025-1108-1
  mode: disabled
dataset:
  name: continual_task_stream_25
  num_tasks: 2
  max_samples_per_task: 50000
  max_seq_length: 1024
  streaming: true
  languages:
  - en
  - de
  - sw
  - fi
  - multi
  tokenizer: NousResearch/Llama-2-7b-hf
training:
  batch_size: 8
  task_epochs: 1
  max_updates_per_task: 50000
  learning_rate: 0.0002
  weight_decay: 0.001
  warmup_steps: 500
  gradient_checkpointing: true
  mixed_precision: bf16
  optimizer: adamw
  lr_scheduler: linear
  grad_accum_steps: 1
  similarity_threshold_tau: 0.8
  fisher_projection_steps: 20
  router_temperature_anneal: linear
evaluation:
  eval_batch_size: 4
  cpu_latency_device: raspberry-pi-4
  primary_metric: retained_accuracy_auc
  secondary_metric: cpu_latency_overhead
optuna:
  n_trials: 0
  direction: maximize
  search_space:
    learning_rate:
      type: loguniform
      low: 1.0e-05
      high: 0.0003
    similarity_threshold_tau:
      type: uniform
      low: 0.75
      high: 0.9
    kd_tree_fanout:
      type: categorical
      choices:
      - 4
      - 8
      - 16
    router_temperature_init:
      type: uniform
      low: 0.5
      high: 2.0
    weight_decay:
      type: uniform
      low: 0.0
      high: 0.01
model:
  backbone:
    name: NousResearch/Llama-2-7b-hf
    quantisation: 4-bit QLoRA
    frozen: true
  adapter:
    type: HIMALAYA
    core_dictionary:
      num_atoms: 24
      init: isotropic
    elastic_dictionary:
      max_atoms: 16
      index: learnable_kd_tree
      quantisation_bits: 3
    router:
      hidden_params: 45000
      expected_active_atoms: 3
      temperature_init: 1.0
    coeff_precision_bits: 8
    total_parameter_budget_mb: 2.5
  kd_tree:
    fanout: 8
    leaf_size: 4
  norm_rescaling: true
run_id: proposed-iter1-Llama-2-7B-HF-4-bit-QLoRA-7-B-parameters
method: proposed
method_name: HIMALAYA
hardware:
  gpu_type: A100-80GB
  max_gpu_mem_gb: 80
